---
name: HTML-Prototype
version: 1.22
author:
  - |-
    Sebastian Riedel, C<sri@oook.de>
    Marcus Ramberg, C<mramberg@cpan.org>
abstract: Generate HTML and Javascript for the Prototype library
license: perl
requires:
  Class::Accessor::Fast: 0
provides:
  HTML::Prototype:
    file: lib/HTML/Prototype.pm
    version: 1.22
generated_by: Module::Build version 0.26
