---
name: HTML-Prototype
version: 1.40
author:
  - |-
    Sascha Kiefer, C<esskar@cpan.org>
    Sebastian Riedel, C<sri@oook.de>
    Marcus Ramberg, C<mramberg@cpan.org>
abstract: Generate HTML and Javascript for the Prototype library
license: perl
requires:
  Class::Accessor::Fast: 0
  HTML::Tree: 0
provides:
  HTML::Prototype:
    file: lib/HTML/Prototype.pm
    version: 1.40
  HTML::Prototype::Controls:
    file: lib/HTML/Prototype/Controls.pm
  HTML::Prototype::DragDrop:
    file: lib/HTML/Prototype/DragDrop.pm
  HTML::Prototype::Effects:
    file: lib/HTML/Prototype/Effects.pm
  HTML::Prototype::Helper:
    file: lib/HTML/Prototype/Helper.pm
  HTML::Prototype::Helper::Tag:
    file: lib/HTML/Prototype/Helper/Tag.pm
  HTML::Prototype::Js:
    file: lib/HTML/Prototype/Js.pm
generated_by: Module::Build version 0.2611
